{{- if .Values.backend.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-server
      nodePort: {{ .Values.backend.service.nodePort }}
    - name: debug
      protocol: TCP
      port: 5005
      targetPort: debug
      nodePort: {{ .Values.backend.service.nodePortForDebug }}
{{- end }}