{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: json-logging
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=70 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=./heapdump"
            - name: SERVER_PORT
              value: "{{ .Values.backend.env.SERVER_PORT }}"
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.backend.env.SPRING_DATASOURCE_URL }}"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          ports:
            - name: http-server
              containerPort: {{ .Values.backend.env.SERVER_PORT }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.backend.env.SERVER_PORT }}
            initialDelaySeconds: 300
            periodSeconds: 5
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 2
            httpGet:
              path: /actuator/health
              port: {{ .Values.backend.env.SERVER_PORT }}
{{- end }}