{{- if .Values.backend.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.env.SERVER_PORT }}
      targetPort: http-server
      nodePort: {{ .Values.backend.service.nodePort }}
{{- end }}