{{- if and .Values.backend.enabled .Values.backend.debug.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-debug-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManagerClusterIssuer }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Disable SSL redirect for debug
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
  - host: debug.{{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5005
  tls:
    - hosts:
        - debug.{{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.secretName }}-debug
{{- end }}