apiVersion: v1
kind: ConfigMap
metadata:
  name: openshelf-flyway-sql
data:
  V1__init.sql: |-
{{ .Files.Get "sql/V1__init.sql" | indent 4 }}
{{- if .Values.flyway.fakeData }}
  V2__data.sql: |-
{{ .Files.Get "sql/V2__data.sql" | indent 4 }} 
{{- end }}
  V3__user_status.sql: |-
{{ .Files.Get "sql/V3__user_status.sql" | indent 4 }}
  V4_migration_schema.sql: |-
{{ .Files.Get "sql/V4_migration_schema.sql" | indent 4 }} 
