apiVersion: v1
kind: ConfigMap
metadata:
  name: openshelf-flyway-sql-part1
data:
  V1__init.sql: |-
{{ .Files.Get "sql/V1__init.sql" | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openshelf-flyway-sql-part2
data:
  V2__data-part1.sql: |-
{{ .Files.Get "sql/V2__data_part1.sql" | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openshelf-flyway-sql-part3
data:
  V2__data-part2.sql: |-
{{ .Files.Get "sql/V2__data_part2.sql" | indent 4 }} 
