apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "openshelf.fullname" . }}-flyway
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: flyway
          image: "{{ .Values.flyway.image.repository }}:{{ .Values.flyway.image.tag }}"
          args: ["migrate"]
          env:
            - name: FLYWAY_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecret }}
                  key: {{ .Values.postgresql.auth.secretKeys.userPasswordKey }}
            - name: FLYWAY_URL
              value: "jdbc:postgresql://{{ include "openshelf.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
          volumeMounts:
            - name: sql
              mountPath: /flyway/sql
      volumes:
        - name: sql
          configMap:
            name: {{ include "openshelf.fullname" . }}-flyway-sql
      restartPolicy: Never 