{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: {{ .Values.frontend.service.type | quote }}
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-server
      {{- if .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
{{- end }}