{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: http-server
      nodePort: {{ .Values.frontend.service.nodePort }}
{{- end }}