apiVersion: v2
name: openshelf-chart
description: A Helm chart for deploying OpenShelf
type: application
version: 0.1.11
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
