# PostgreSQL settings
postgresql:
  enabled: false
  primary:
    persistence:
      enabled: true
      size: 10Gi
  auth:
    username: openshelf_user
    database: openshelf
# Backend settings
backend:
  enabled: false
  image:
    repository: ghcr.io/theopenshelf/platform-api
    tag: latest
  replicaCount: 2
  service:
    type: NodePort
    port: 80
    nodePort: 30096
  env:
    # Spring properties
    SERVER_PORT: 8486
    SPRING_PROFILES_ACTIVE: dev
    SPRING_DATASOURCE_USERNAME: openshelf_user
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql.platform.svc.cluster.local:5432/openshelf

ingress:
  host: oshelf.org
  certManagerClusterIssuer: letsencrypt-prod
  secretName: letsencrypt-platform

# Frontend settings
frontend:
  enabled: true
  image:
    repository: ghcr.io/theopenshelf/platform-ui
    tag: latest
  replicaCount: 1
  service:
    type: NodePort
    port: 80
    nodePort: 30095
  env:
    API_URL: https://oshelf.org/api
